name: Deploy Laravel to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
        npm install && npm run build || true

    - name: Upload via SFTP
      uses: pressidium/lftp-mirror-action@v1.0.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        user: ${{ secrets.SFTP_USERNAME }}
        pass: ${{ secrets.SFTP_PASSWORD }}
        localDir: '.'  
        remoteDir: ${{ secrets.SFTP_REMOTE_PATH }}
        options: '--delete --verbose --exclude .git --exclude .gitattributes --exclude .github --exclude .gitignore --exclude node_modules --exclude tests --reverse --only-newer'
